//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Athletes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athletes()
        {
            this.Results = new HashSet<Results>();
        }
    
        public int IDAthlete { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int IDCountry { get; set; }
        public int IDSport { get; set; }
        public System.DateTime Data { get; set; }
        public int IDPicture { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Pictures Pictures { get; set; }
        public virtual Sports Sports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}
