//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OlympicsEntities3 : DbContext
    {
        public OlympicsEntities3()
            : base("name=OlympicsEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Athletes> Athletes { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Medals> Medals { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
        public virtual DbSet<Results> Results { get; set; }
        public virtual DbSet<Sports> Sports { get; set; }
        public virtual DbSet<TypeOfOlympiads> TypeOfOlympiads { get; set; }
    }
}
